---
name: Docs 📚

on:
  push:
    branches:
      - main
    paths:
      - "inst/templates/**"
      - "_pkgdown.*"
      - DESCRIPTION
      - "**.md"
      - "**.Rmd"
      - "man/**"
      - "LICENSE.*"
      - NAMESPACE
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
    paths:
      - "inst/templates/**"
      - "_pkgdown.*"
      - DESCRIPTION
      - "**.md"
      - "**.Rmd"
      - "man/**"
      - "LICENSE.*"
      - NAMESPACE
  workflow_dispatch:

jobs:
  docs:
    steps:
      uses: quarto-dev/quarto-actions/setup@v2
      name: Pkgdown Docs 📚
      uses:  ./.github/workflows/pkgdown.yaml
      secrets:
        REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
      with:
        default-landing-page: latest-tag
        additional-unit-test-report-directories: unit-test-report-as-cran
        deps-installation-method: setup-r-dependencies
