---
name: Docs 📚

on:
  push:
    branches:
      - main
    paths:
      - "inst/templates/**"
      - "_pkgdown.*"
      - DESCRIPTION
      - "**.md"
      - "**.Rmd"
      - "man/**"
      - "LICENSE.*"
      - NAMESPACE
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
    paths:
      - "inst/templates/**"
      - "_pkgdown.*"
      - DESCRIPTION
      - "**.md"
      - "**.Rmd"
      - "man/**"
      - "LICENSE.*"
      - NAMESPACE
  workflow_dispatch:

jobs:
  docs:
    name: install deps
    run: |
      install.packages("remotes")
      install.packages("quarto")
      remotes::install_github("quarto-dev/quarto-r")
      remotes::install_github("https://github.com/insightsengineering/bsafe")
      options(quarto.quiet = FALSE)
    shell: Rscript {0}
    name: Pkgdown Docs 📚
    uses:  ./.github/workflows/pkgdown.yaml
    secrets:
      REPO_GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
    with:
      default-landing-page: latest-tag
      deps-installation-method: setup-r-dependencies
